### ISSUE TITLE
Cannot read properties of undefined (reading 'dragging')

### ISSUE THREAD

**Issue by cyberiumchain** [GreenFlag31/carousel-library#1]
ERROR TypeError: Cannot read properties of undefined (reading 'dragging')
    at _c6 (/app/node_modules/ngx-carousel-ease/fesm2022/ngx-carousel-ease.mjs:941:49)
    at executeTemplate (/app/node_modules/@angular/core/fesm2022/core.mjs:12314:9)
    at refreshView (/app/node_modules/@angular/core/fesm2022/core.mjs:13541:13)
    at detectChangesInView (/app/node_modules/@angular/core/fesm2022/core.mjs:13765:9)
    at detectChangesInViewIfAttached (/app/node_modules/@angular/core/fesm2022/core.mjs:13728:5)
    at detectChangesInComponent (/app/node_modules/@angular/core/fesm2022/core.mjs:13717:5)
    at detectChangesInChildComponents (/app/node_modules/@angular/core/fesm2022/core.mjs:13778:9)
    at refreshView (/app/node_modules/@angular/core/fesm2022/core.mjs:13591:13)
    at detectChangesInView (/app/node_modules/@angular/core/fesm2022/core.mjs:13765:9)
    at detectChangesInViewIfAttached (/app/node_modules/@angular/core/fesm2022/core.mjs:13728:5)

Environment: MACOS 14.3. Angular 17, Node 20, NPM 10

**Comment by GreenFlag31** [comment]
Hi,

It seems to be a race condition error due to evaluating a variable in the template (at executeTemplate...) before this variable got initialised. Therefore, I've have published a new version on npm (v0.1.1) giving a default value for variables in the template and pushing initialisation in AfterViewInit. 

Could you npm i the latest version, and provide me feedback in case of persisting error? 

In case of persisting error:
* Could you share your carousel configuration? 
* In which context do you get the error? CSR, SSR? 
* What step/action do you do to get the error?
* Is the carousel still working with the error?

Please share any other relevant details.


Thank you

**Comment by cyberiumchain** [comment]
Sure. will do. TIA

**Comment by cyberiumchain** [comment]
The issue is gone. Wonderful !
